# Generated by Django 4.0.3 on 2022-04-17 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='created',
            new_name='time_created',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='updated',
            new_name='time_updated',
        ),
    ]
