# Generated by Django 4.0.3 on 2022-04-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0003_alter_metadata_dataset_progress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='metadata_id',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='metadata_name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
