# Generated by Django 4.0.3 on 2022-04-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0004_alter_metadata_metadata_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadata',
            name='science_keywords',
        ),
        migrations.AddField(
            model_name='metadata',
            name='science_keywords',
            field=models.ManyToManyField(to='metadata.sciencekeyword'),
        ),
    ]
