# Generated by Django 4.0.3 on 2022-04-24 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0005_remove_metadata_science_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sciencekeyword',
            name='full_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
