# Generated by Django 4.0.3 on 2022-05-14 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0006_sciencekeyword_full_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sciencekeyword',
            options={'ordering': ('full_name',)},
        ),
        migrations.AlterField(
            model_name='metadata',
            name='metadata_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
